### ISSUE TITLE
Overscrolling in Google Chrome

### ISSUE THREAD

**Issue by mattwaler** [Caldis/Mos#160] opened 2019-08-08 19:28 UTC
**Describe the bug | 问题描述**

When using this app with google chrome, I constantly encounter a bug where I can scroll infinitely past the header and footer of webpages.

**To Reproduce | 如何重现**

Use the application in Chrome, resize the browser / open dev tools, interact with the site, etc, and eventually you will be able to overscroll

**Expected behavior | 期望结果**

Webpage does not allow the user to overscroll the page bounds.

**Screenshots | 相关截图**

**System Info | 系统信息:**
-  Application [e.g. Safari, Chrome, Whole System]

**Additional context | 额外说明**

**Comment by Caldis** [comment] 2019-08-21 17:08
I also noticed this problem, but it seems difficult to find a way to reproduce. Perhaps the rolling events generated by Mos in some cases have the same characteristics as the scroll events of the trackpad, causing the browser to act accordingly.

**Comment by mattwaler** [comment] 2019-08-21 17:40
I wish I could find the exact cause but I was unable to do so either!

**Comment by eswierk** [comment] 2019-09-03 03:31
I ran into this condition randomly a few days ago and thought that it had something to do with Mos's Smooth Scrolling feature being enabled, and it hasn't happened since.

But I'm able to reproduce this condition following the steps at https://bugs.chromium.org/p/chromium/issues/detail?id=999221 , even without Mos running. So it does appear to be a Chrome bug, but somehow the MacBook's built-in trackpad doesn't trigger it, while an external trackpad does. And maybe having Smooth Scrolling enabled makes it more likely?

**Comment by noohgnus** [comment] 2019-09-10 15:33
I can reproduce this issue. When you are scrolling at the moment the page is loading, it overscrolls.

**Comment by pietervanheijningen** [comment] 2020-02-19 07:39
I've found a workaround for it for now.
Running this command in terminal and logging out and back disables the rubberbanding in chrome, which fixes the issue:
```bash
defaults write -g NSScrollViewRubberbanding -bool false
```

And then made a "desktop mode" and a "laptop mode" application with automator to be able to toggle this quickly

**Comment by Caldis** [comment] 2020-03-03 11:31
It looks like this is a bug in Chrome, I can still reproduce this bug using MX Anywhere in an environment running only Logitech Options, but using a normal mouse in the same environment will not trigger this problem.
Logitech Options is similar to Mos, and it will re-process the scroll event. Perhaps Chrome has some errors in identifying scroll events with certain characteristics.

**Comment by Caldis** [comment] 2020-03-13 18:12
Another approach https://github.com/Caldis/Mos/issues/234#issuecomment-597420515

**Comment by Caldis** [comment] 2021-02-20 09:13
Fixed in latest versions https://github.com/Caldis/Mos/releases/tag/3.3.1

**Closed by Caldis** 2021-02-20 09:13 UTC
Labels: BUG
