### ISSUE TITLE
Broken "screen magnification with a scroll gesture" when Mos is enabled. 

### ISSUE THREAD

**Issue by EugenTarasenko** [Caldis/Mos#293] opened 2020-08-04 00:06 UTC
**Describe the bug | 问题描述**
Enabled Mos Smooth Scrolling makes ctrl+scroll for screen zooming unusable. Wheel scrolling becomes reversed.
**To Reproduce | 如何重现**
Enable zoom in System Preferences/Accessibility/Zoom. Choose "Use scroll gesture with modifier keys to zoom". In the list select a modifier key (e.g. control key). Enable Mos Smooth Scrolling. Try to magnify the screen by holding the control key and rolling the mouse wheel.
**Screenshots | 相关截图**
![Screenshot 2020-08-04 at 03 02 27](https://user-images.githubusercontent.com/68885351/89238526-09710500-d5ff-11ea-9228-1e286fad8e54.png)
**System Info | 系统信息:**
 - Mouse: Logitech G603
 - OS: macOS 10.15.6
 - Mos Version 3.1.0
 -  Application Whole System

**Comment by Caldis** [comment] 2020-10-17 16:51
I can't reproduce the problem on BigSur, which function did bind for the control key to in Mos?

**Comment by Caldis** [comment] 2021-02-20 09:43
Maybe fixed in latest release https://github.com/Caldis/Mos/releases/tag/3.3.1

**Closed by Caldis** 2021-02-20 09:43 UTC
Labels: BUG

**Comment by EugenTarasenko** [comment] 2021-02-20 14:32
Thank you. Now it works much better.
